apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  VECTORSTORE_HOST: {{ required "appConfig.vectorstore required" .Values.appConfig.vectorstore.host}}
  # beware that integers need to be quoted, otherwise k8s cannot create configmap -.-
  VECTORSTORE_PORT: "{{ required "appConfig.vectorstore required" .Values.appConfig.vectorstore.port}}"
  S3_BUCKET_DOCUMENTS: {{ required "appConfig.aws.documentBucketName required" .Values.appConfig.aws.documentBucketName}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ required "appConfig.aws.keyId required" .Values.appConfig.aws.keyId}}
  AWS_SECRET_ACCESS_KEY: {{ required "appConfig.aws.secretKey required" .Values.appConfig.aws.secretKey}}
  AWS_ROLE_ARN_TO_ASSUME: {{ .Values.appConfig.aws.roleToAssume}}
  OPENAI_API_KEY: {{ required "appConfig.openaiApiKey required" .Values.appConfig.openaiApiKey}}
---
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}